// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrpkalwxudkryctuchaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhycGthbHd4dWRrcnljdHVjaGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0MjY1MDQsImV4cCI6MjA3NjAwMjUwNH0.o_bW7kRtfZxY3DKTM2t3RYidDBHd6ggtGqUrCN2RUTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});